version: "3"

services:
  db:
    image: mysql
    container_name: db_resrel
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_resrel
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker
    container_name: www_resrel
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./api:/var/www
    networks:
      - dev
    #For xDebug
    extra_hosts:
      - host.docker.internal:host-gateway

  app:
    image: node:latest
    container_name: app_resrel
    working_dir: /app
    command: >
      sh -c "npm i && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
