name: ResRel CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          working-directory: api

      - run: echo "Composer dependencies have been installed"
      - run: vendor/bin/phpunit
