name: ResRel CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup and run tests
        working-directory: ./api
        run: |
          cp .env.example .env
          composer install --ignore-platform-req=php
          php bin/phpunit
