name: ResRel CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        # wait for db to be ready
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      # ubuntu latest have php 8.1 preinstalled and app require 8.2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Load fixtures
        working-directory: ./api
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "DROP DATABASE IF EXISTS test"
          mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE test"

      - name: Setup composer
        working-directory: ./api
        run: |
          cp .env.example .env
          composer install --ignore-platform-req=php

      - name: Generate JWT keys
        working-directory: ./api
        run: php bin/console lexik:jwt:generate-keypair

      - name: Start Symfony server
        working-directory: ./api
        run: php bin/console server:start --detach

      - name: Run tests
        working-directory: ./api
        run: php bin/phpunit
      #todo - setup db
