name: ResRel CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # ubuntu latest have php 8.1 preinstalled and app require 8.2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Setup composer
        working-directory: ./api
        run: |
          cp .env.example .env
          composer install --ignore-platform-req=php

      - name: Generate JWT keys
        working-directory: ./api
        run: php bin/console lexik:jwt:generate-keypair

      - name: Create Database
        run: |
          mkdir -p data
          touch data/database.sqlite

      - name: Migrate database
        working-directory: ./api
        run: php bin/console d:m:m --no-interaction --env=test

      - name: Loading fixtures
        working-directory: ./api
        run: php bin/console d:f:l --no-interaction --env=test

      - name: Run tests
        working-directory: ./api
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/var/database_test.db
        run: php bin/phpunit
      #todo - setup db
