name: ResRel CI

on: [push]

jobs:
  phpunit:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Setup and run tests
        working-directory: ./api
        run: |
          cp .env.example .env
          composer install
          php bin/phpunit
